##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile for SDL graphic library.
##

include	../../mk_tools/pre_load.mk

PROJECT_LANGUAGE	:=	"C++"

PROJECT_BINARY_TYPE	:=	"SHARED"

PROJECT_BINARY_NAME	:=	"_arcade_sdl"

PROJECT_LIB	:=	-lSDL2 -lSDL2_ttf -lSDL2_image

PROJECT_INCLUDE	:=	-I../../include/graphics/	\
			-I../../include/shared/		\
			-I./include/

PROJECT_SRC	:=	./src/SdlModule.cpp	\
			./src/init.cpp

LIB_BINARY_MOVE_TO	:=	"../"

include	../../mk_tools/autoloader.mk
