##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile for the pacman game library.
##

include	../../mk_tools/pre_load.mk

PROJECT_LANGUAGE	:=	"C++"

PROJECT_BINARY_TYPE	:=	"SHARED"

PROJECT_BINARY_NAME	:=	"_arcade_pacman"

PROJECT_INCLUDE	:=	-I../../include/games/	\
			-I../../include/shared/	\
			-I./include/

PROJECT_SRC	:=	./src/PacmanModule.cpp	\
			./src/init.cpp

LIB_BINARY_MOVE_TO	:=	"../../games/"

include	../../mk_tools/autoloader.mk
