##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile for tools library.
##

include	../../mk_tools/pre_load.mk

PROJECT_LANGUAGE	:=	"C++"

PROJECT_BINARY_TYPE	:=	"STATIC"

PROJECT_BINARY_NAME	:=	"tools"

PROJECT_INCLUDE	:=	-I./include/

PROJECT_SRC	:=	./src/Exception.cpp	\
			./src/Log.cpp

include	../../mk_tools/autoloader.mk
